### PR TITLE
Iterative signature algorithm for dalcotidine.

### PR DESCRIPTION
**Pull request by rrueedi**
Tested and working on local phenomenal instance. I am unclear why line 308 in `config/phenomenal_tools2container.yaml` still shows `v0.2.0_cv0.4.62` as value for `docker_tag_override`. The change to ` v0.2.1_cv0.4.1.64` was already introduced in commit #222

### CODE REVIEW

**Comment by korseby** [comment]
Hi @rrueedi , I merged the master branch with develop and triggered a new build in jenkins. The version tag for the release is: v0.1_cv0.1.27

**Comment by pcm32** [comment]
Please merge to release branch if this is for the release. Thanks.

**Comment by pkrog** [comment]
Hi @rrueedi , your tag `v0.2.1_cv0.4.1.64` is wrong, as the container version defined in your container repository Dockerfile cannot have 3 figures. I've looked at `phnmnl/container-iterative-signature-algorithm` repository, and I understand the tag found by @korseby . In your `Dockerfile` the `version` and the `software.version` labels are both defined to `0.1`. Please set them to the appropriate values if needed. `version` refers to the container version and must have two numbers like `1.2`, and `software.version` refers to your tool version and can be any form but preferably three figures like `1.2.3`.

**Comment by pkrog** [comment]
And, if you want that PR to be merged for the dalcotidine release, please change the target branche from `develop` to `release/18.01_dalcotidine`.

**Comment by rrueedi** [comment]
@pkrog : you're referring to two different containers, so here's what I did:
I've updated the Dockerfile in https://github.com/phnmnl/container-metabomatching to use an x.y version format instead of x.y.z. The new tag, as per Jenkins, for metabomatching is `v0.2.1_cv0.5.67`

This branch, however, is to insert https://github.com/phnmnl/container-iterative-signature-algorithm into Galaxy. For this container, the tag `v0.1_cv0.1.27` is correct. I therefore made no changes.

I am indeed looking for both of these changes to be merged into dalcotidine. So I'll change the target branch for this merge. But what about metabomatching? @ilveroluca merged the new branch into develop [#222], then deleted the branch. It doesn't look like the changes carried over into `release/18.01_dalcotidine`, so do I redo the branch and a new merge request?

**Comment by korseby** [comment]
There are some unresolved issues now probably caused by going to release-18.01.

@rrueedi : 
- Please fix the external-datatypes/no_unzip_datatypes. Leftover from merge.
- Where are the other tools in rehsape2 come from, melt and cast? And what about postProcessing/fingerprintclustering? 
- Please fix simplified_galaxy_stable_container_creation.sh, leftover from merge.
- in various OpenMS tools you change to:
```<param name="param_in" type="data" format="txt"```. Please verify that this is correct.
- Please remove the change in: tools/phenomenal/ms/metfrag.xml . This will be handled by @c-ruttkies .

**Comment by rrueedi** [comment]
@pkrog  @korseby 
None of those are my changes, of course. I suppose develop was farther along than release/v18.01-dalcotidine. I'm closing this request, and starting anew.

**Pull request closed without merging**
