### PR TITLE
Feature/fluxomics escher

### PR DESCRIPTION
**Pull request by pcm32**
This PR introduces a visualization through metabolic pathways viewer Escher for fluxomics data.

### CODE REVIEW

**Comment by pcm32** [comment]
Don't merge yet if reviewing please... forgot to add a workflow file for this tool with the rest of the fluxomics pipeline!

**Comment by pcm32** [comment]
I have added now the workflow definition. Could either @ilveroluca or @djcomlab review please? Thanks!

**Comment by djcomlab** [comment]
Looks good to me!

**Comment by pcm32** [comment]
Thanks @djcomlab!

**Pull request merged**
