### PR TITLE
Update ramid tool with more complex CDF files

### PR DESCRIPTION
**Pull request by seliv55**
The tool ramid upgraded to read more complex CDF files and prepared for a new release. The input/output formats are not changed.

### CODE REVIEW

**Comment by pcm32** [comment]
This sort of PR should go against the release branch.

**Comment by djcomlab** [comment]
Shouldn't all PRs go to `develop` until after the tool freeze (Friday)?

**Comment by seliv55** [comment]
I updated here the version number for midcor also, and pushed the change again. Sorry that I made the same error in the message. It should be "prepared release version for midcor".

**Comment by seliv55** [comment]
updated version number for iso2flux

**Pull request merged**
