### PR TITLE
Improved layout of tools (Philippe's and Reza's)

### PR DESCRIPTION
**Pull request by pcm32**
This PR takes the work of @rsalek, @proccaserra and others in issue #75 . Given that #114 carries some additional commits on isa tools and was outdated in terms of tools to include (a few missing), I started this new PR to leave #114 to the isa tools only. This PR should be merged and then #114.

- This is a cherry pick of the tool_conf commit 15370001acc047210359c2ddecd48a1de80e7597 in #114 
- Compared to latest dev / release to include all tools available so far in those branches, resolving conflicts.
```
# on the different branches:
grep 'tool file' config/tool_conf.xml | awk -F'"' '{ print $2 }' | sort -u
# and diff of those outputs
```
- No missing tools.
- Works on minikube

Will rename #114 .

@ilveroluca @proccaserra @pkrog if I could get a blessing from any of you, it would be good to merge this quickly to avoid missing more tools as other PR's are merged. Thanks!

### CODE REVIEW

**Comment by pkrog** [comment]
Some W4M tools are not in the right place:
 * `NmrNormalization` should be inside the `pheno-stats` section. Despite its (historical) name, it is not an NMR tool. The name displayed to the user is simply `"Normalization"`.
 * `lcmsmatching` should be under the `phenomenal-annot` label or under the `"phenomenal-ms` label or both.
 * `isa2w4m` should be inside the `pheno_convert_metadata` section or the `isa-tools` sections or both.
 * `generic_filter` and `qualitymetrics` should be in the `pheno-stats` section.

**Comment by rsalek** [comment]
I agree with @pkrog

**Comment by rsalek** [comment]
Btw, couldn't f find a way to duplicate entries last I checked. Any suggestions?

**Comment by pcm32** [comment]
Thanks @pkrog, I have updated as you suggest. Can you re-review? I have tested in Minikube and looks good.

**Comment by pcm32** [comment]
Please review soon so that we can merge and then base tours on this new layout. Thanks!

**Comment by pkrog** [comment]
That looks fine for me, you can merge.

**Comment by proccaserra** [comment]
@pcm32 @pkrog  I wasn't aware of these tools. thx for the input. one question to be sure
the tool_conf refers to       <tool file="phenomenal/w4m/NmrNormalization_xml.xml" labels="W4M"/>

is the file name really NmrNormlization_xml.xml ? or should it be renamed       NmrNormalization.xml" labels for simplicity? this is minor and does not block the merge

**Comment by pcm32** [comment]
Yes, I have checked now, and that is the name. We need to be alert for any missing tools in the UI, though I have checked the XML to contain everything, it might be that Galaxy might not render some sections.

**Comment by pcm32** [comment]
Thanks for looking into it guys!

**Pull request merged**
