### PR TITLE
performs unsupervised clustering and automatically determine the best number of cluster<

### PR DESCRIPTION
**Pull request by ecamenen**
Hi !
I've added a new tool developed by INRA: fingerprint_Clustering. The README is completed and the minikube tests work.
Please do not hesitate if any informations is missing.
Etienne C.

### CODE REVIEW

**Comment by sneumann** [comment]
Could you rebase your commit on the newest devel branch, currently there is a merge conflict. Thanks, Steffen

**Comment by ecamenen** [comment]
I can't check the rebase manually, is it good now ? Otherwise, I'll create another PR (gitkraken don't seem to like rebase and re-PR)

**Comment by djcomlab** [comment]
This needs to be rebased again.

**Comment by ecamenen** [comment]
This was an old, obsolete PR to be deleted.
After some changes, GitKraken 've done a duplication with PR #203 fingerprint clustering onto develop, and this last PR was the one that have been approved last friday.

**Pull request closed without merging**
