### PR TITLE
sib/v18.01 dalcotidine

### PR DESCRIPTION
**Pull request by rrueedi**
Changes for iterative-signature-algorithm and metabomatching tools for dalcotidine release.

### CODE REVIEW

**Comment by rrueedi** [comment]
metabomatching itself changed (`docker_tag_override: v0.2.1_cv0.5.67`) but there was no need to change the Galaxy wrapper.

**Comment by pkrog** [comment]
Hi @rrueedi , yes we understand that only the container tag has been updated for metabomatching, however for the sake of clarity, as stated by @korseby , could you please make another pull request (hence from another branch) for the  metabomatching container tag upgrade, and remove that line from this iterative-signature-algorithm PR?

**Comment by korseby** [comment]
The release of metabomatching will be done by @c-ruttkies  :)

**Comment by rrueedi** [comment]
I'm not sure, but I created new pull requests to separate changes related from metabomatching 
[#237] and iterative-signature-algorithm [#238].

**Pull request closed without merging**
