### PR TITLE
calculates distance between metabolites in a network

### PR DESCRIPTION
**Pull request by ecamenen**
Hi steffen,
Another tool from last INRA's development. This one have been rebased on dalcotidine version.
Etienne C.

### CODE REVIEW

**Comment by ecamenen** [comment]
Done container's version update

**Comment by djcomlab** [comment]
`dev_` prefix is added when you push changes to the `develop` branch of `container-fingerprintSubnetwork`, which looking at the network graph is the latest changes pushed.

You need to merge the changes to `master` (and possibly bump a small version increment to make it build - sometimes it doesn't build if it's identical to `develop`). The tags built from `master` do not have `dev_`.

**Comment by ecamenen** [comment]
- I've created a new version for my container-fingerprintSubnetwork on master. I think the problem was just related to the fact that I get used to do 'git push origin master develop' and that's just launched a jenkins' job both for master and develop.
- I've updated the config/...tools2container.yaml (and some minor modification about the SBML version information in pathwayenrichment.xml after discussion with a colleague).

I hope everything work now !
Yours,
Etienne

**Comment by michaelvanvliet** [comment]
Hi Etienne, do you want to switch to the updated container v1.1_cv1.3.4 ?

**Comment by ecamenen** [comment]
Sorry, I don't understand the question. I've changed the number of the container to the one from the last Jenkins build because there was a bug with the previous tag job (dev_ prefix).
So, yes, I want to use this v1.1_cv1.3.4 tag for the config/phenomenal_tools2container.yaml file

**Pull request merged**
