### PR TITLE
Upgrade biosigner tool.

### PR DESCRIPTION
**Pull request by pkrog**

### CODE REVIEW

**Comment by pkrog** [comment]
I'm unable to test at the moment in minikube. It gives the message: `0/1 nodes are available: 1 Insufficient cpu.`.

**Comment by rrueedi** [comment]
@pkrog I've had this problem too. Try changing the performance settings to use 0.5 CPU; that worked for me.

**Comment by pkrog** [comment]
Hi @rrueedi , sorry I fail to understand, where should I should set that setting?

**Comment by rrueedi** [comment]
On the tool page in Galaxy, below the tool parameters, there should be a performance settings box. There's 4 settings, 2 for CPU, 2 for RAM. If you set the 2 for CPU to 0.5 each (instead of 0), the tool should run. (Assuming you're having the same issue I was.)

**Comment by pkrog** [comment]
Thanks @rrueedi , I used though another trick to get tests passing. Please @ilveroluca , could you review?

**Pull request merged**
