### PR TITLE
[WIP] Feature/factors summary fix

### LINKED ISSUE #134: Missing factors_summary tool
Looks like  `factors_summary` tool that generates some JSON that is a factors summary of a ISA-Tab study has gone missing. Maybe accidentally removed during the tools reorgranization.

### PR DESCRIPTION
**Pull request by pcm32**
Aims to fix #134 issue. Please @djcomlab take a look at the content of the wrapper and test on minikube if possible, I'm not sure if you introduced changes on how the tool is called. Apparently the file was wrongly copied when re-organising.

### CODE REVIEW

**Comment by ilveroluca** [comment]
Hmm...ok, there's a problem.  I may have even introduced it myself.  This patch won't fix it though.  The command line parsing of `run_mtblisa.py` has changed since that old wrapper was generated.

**Comment by ilveroluca** [comment]
I have updated the wrapper for the current argument parsing scheme used by `run_mtblisa.py`.  Needs testing to ensure correctness.

**Comment by pcm32** [comment]
Sorry @ilveroluca, might be that this is superseded by a larger PR from @djcomlab... Can you comment David?

**Comment by djcomlab** [comment]
@pcm32 I think I've already brought this back in another branch `isa_updates_for_cerebellin`, so this might be superseded entirely...

**Comment by pcm32** [comment]
Thanks @djcomlab will close!

**Pull request closed without merging**
