### PR TITLE
Feature/workflow sharing

### PR DESCRIPTION
**Pull request by kikkomep**
This PR enables workflow sharing through Galaxy API and fixes the API KEY creation of the Galaxy administrator.

### CODE REVIEW

**Comment by kikkomep** [comment]
Hi @pablo. The only issue in minikube is related to the BioBlend version: the _container-galaxy-k8s-runtime_ comes with the requirements specified in `lib/galaxy/dependencies/pinned-requirements.txt` and specifically with BioBlend 0.7.0, which is quite old (we need the latest 0.9.0 version of BioBlend). Updating the `pinned-requirements.txt` is not sufficient because when the dependencies are installed the `https://wheels.galaxyproject.org/simple` repository is used https://github.com/phnmnl/container-galaxy-k8s-runtime/blob/9ae06c1008e51eafa64670ee206fc4529dffa02d/Dockerfile#L29-L30 ... and it doesn’t contain the latest version of BioBlend. 
Updating BioBlend via `pip install --upgrade bioblend` also other packages are updated (i.e.,`boto, certifi, chardet, idna, pyyaml, requests, requests-toolbelt, urllib3`). 
What would you suggest?

**Comment by pcm32** [comment]
Hi @kikkomep apologies for the lack of attention, deliverable writing and checking has been consuming us here. Which part of the new functionality requires bioblend 0.9? Is it the API key part? Because that we could sort out in a different way.

**Comment by kikkomep** [comment]
Hi @pablo! 
Yes, it is the API key part. Specifically, the method `get_users_apikey` used here
https://github.com/phnmnl/container-galaxy-k8s-runtime/blob/f227cf112cf619cb1cccef7acca4faa953633bd7/ansible/configure_galaxy.py#L155
to check whether the `admin_user` already has an API Key is not available on BIoBlend 0.7.

**Comment by pcm32** [comment]
By the way, the pablo handler is not mine, hehehe.

I would suggest that we limit this PR to the workflow part then, and we can leave the api key issue for later. Currently we add one from outside initially and then delete it. We could leave this as a permanent API key. Is not recommended but would allow us to escape from the problem in the meantime bioblend is not used in galaxy as 0.9.

Could you then remove the user API key parts?

Thanks!

**Comment by kikkomep** [comment]
@pcm32 Ops... sorry :disappointed:
Ok! The API Key part has been removed!

**Comment by kikkomep** [comment]
Yes, it works on minikube!

**Pull request merged**
