### PR TITLE
Updates to isatools tools

### PR DESCRIPTION
**Pull request by djcomlab**
Various updates to `isatools` related tools, in preparation for tool freeze for `v18.01-dalcotidine` release.

### CODE REVIEW

**Comment by djcomlab** [comment]
Note I will fix the container version numbers when pulling into the release branch (`latest` is currently easier for develop purposes).

**Comment by c-ruttkies** [comment]
Can you add resources="all" to the line where you defined <tool id="mtbls-labs-uploader" destination="dynamic-k8s-small"/> in job_conf.xml? I think this was necessary.

**Comment by djcomlab** [comment]
Thanks @c-ruttkies, well spotted!

**Comment by djcomlab** [comment]
This should go into `develop` but also into the D-release branch. #220 fixes container versions for the release. I like to leave my containers to `latest` in `develop` for ease of testing/development when I need to make updates to the containers.

**Comment by pcm32** [comment]
Release branch will be merged (when releasing) to develop, so it will make it to develop eventually. You should merge to develop (and not the release) if you dont't want something on the release, but for the next one. Not sure you should merge to both, goes against the release branching pattern.

**Comment by ilveroluca** [comment]
This looks ok to me.  Galaxy starts up fine and doesn't report any errors.  I haven't done any more in-depth testing, but I'm sure @djcomlab has :-)

**Comment by djcomlab** [comment]
Thanks @ilveroluca ... I had one more fix just committed. Now I'm done!

**Comment by djcomlab** [comment]
Ahh @proccaserra spotted some other small bugs so won't merge it quite yet!

**Pull request merged**
