### PR TITLE
Tidy up job_conf and tool_conf to avoid latests and dev tags

### PR DESCRIPTION
**Pull request by pcm32**
This PR aims to tidy up some job_conf and tool_conf to get rid of tools that were delayed for the release and to make sure that tools included are all on release tags.

Please @korseby and @c-ruttkies take a look, to see if we need to revert any of this.

### CODE REVIEW

**Comment by c-ruttkies** [comment]
Thx @pcm32. I am fine with the PR.

**Comment by pcm32** [comment]
Still [WIP] please DO NOT MERGE.

**Comment by pcm32** [comment]
I will merge this commit by commit since we might need to reverse parts if there are issues.

**Comment by pcm32** [comment]
With thanks to Mathias Walzer from PRIDE@EBI for helping me with the OpenMS resource settings.

**Pull request merged**
