### PR TITLE
fixed configs

### PR DESCRIPTION
**Pull request by ArturasG**
Adding tameNMR.

The XMLs work and I am able to run the tools in the test environment. There are a couple of packages missing making a couple tools to not run properly but I'll modify the Dockerfile for the tool container asap (tonight). Other than that I think it should all be good.

### CODE REVIEW

**Comment by korseby** [comment]
Hi Arturas,

sorry I have missed your pull request here.

PR looks fine to me.

Instead of "latest" you probably should use the version of the container: dev_v1.0_cv0.5.9.

Best wishes, *Kristian

**Comment by djcomlab** [comment]
If this is going to be part of the D-release, please get Jenkins to build your container on `master` to generate a tag without `dev_`.

**Comment by korseby** [comment]
Hi, I merged develop into master and triggered a new jenkins build. I replaced "latest" with the version in the stable release: 1.0_cv0.5.10

**Comment by ilveroluca** [comment]
The last two commits:
1. fix a typo in the ttest wrapper
2. insert a prefix `tamenmr-` to all new tools ids in this PR.

I still generate the following warnings as Galaxy starts up.  It would be nice to fix them as they seem to be indicating problems with the wrappers.

```
galaxy.tools WARNING 2018-07-02 16:10:34,616 Tool tamenmr-normalise_data: a when tag has not been defined for 'method_choice (method) --> totInt', assuming empty inputs.
galaxy.tools WARNING 2018-07-02 16:10:34,616 Tool tamenmr-normalise_data: a when tag has not been defined for 'method_choice (method) --> PQN', assuming empty inputs.
galaxy.tools WARNING 2018-07-02 16:10:34,619 Tool tamenmr-normalise: a when tag has not been defined for 'method_choice (method) --> totInt', assuming empty inputs.
galaxy.tools WARNING 2018-07-02 16:10:34,619 Tool tamenmr-normalise: a when tag has not been defined for 'method_choice (method) --> PQN', assuming empty inputs.
galaxy.tools WARNING 2018-07-02 16:10:34,621 Tool tamenmr-pca: a when tag has not been defined for 'group_choice (group) --> N', assuming empty inputs.
galaxy.tools WARNING 2018-07-02 16:10:34,630 Tool tamenmr-plotnmr: a when tag has not been defined for 'groups_choice (factCond) --> N', assuming empty inputs.
galaxy.tools WARNING 2018-07-02 16:10:34,631 Tool tamenmr-plotnmr: a when tag has not been defined for 'aggr_choice (aggr) --> N', assuming empty inputs.
galaxy.tools WARNING 2018-07-02 16:10:34,631 Tool tamenmr-plotnmr: a when tag has not been defined for 'plotBins_choice (plotBins) --> N', assuming empty inputs.
galaxy.tools WARNING 2018-07-02 16:10:34,643 Tool tamenmr-prepPattern: a when tag has been defined for 'method_choice (method) --> intelligent', but does not appear to be selectable.
```

**Pull request merged**
