### PR TITLE
Add tool simid

### PR DESCRIPTION
**Pull request by seliv55**

### CODE REVIEW

**Comment by pcm32** [comment]
Hi @seliv55 what needs to happen is that all changes related to the addition of simid need to go in the same pull request, not all on separate pull requests.

For this you need to update your local copy of this repo (in particular de develop branch), branch from there to a `feature/simid-addition` (name is irrelevant of course, but if meaningful better) branch, put all your changes there, make sure it runs well on minikube locally, push that branch to this repo and then make a pull request, explaining what is the pull request about.

Thanks!
Pablo

**Comment by seliv55** [comment]
Thanks Pablo, I will do in this manner

**Comment by seliv55** [comment]
Thanks Pablo, I will do in this manner

**Comment by pcm32** [comment]
Let me know if you need help with this. You could just for instance stand in one of your branches (possibly the on on this PR) and then cherry pick the changes in the other branches you created, so that they are added to this branch.

**Comment by seliv55** [comment]
@pcm32 , OK, thanks Pablo, I am going now to install minicube in my PC and check if it works with Galaxy. I'll let you know.

**Comment by sneumann** [comment]
This is superseded by #179

**Pull request closed without merging**
