### PR TITLE
Initial version of mzQuality

### PR DESCRIPTION
**Pull request by michaelvanvliet**
The first basic functionality of mzQuality available in the PhenoMeNal Galaxy environment. It includes an updated version of the vendor format converter and a collection of tools to assess the quality of targeted Metabolomics experiments using LC/GC-MS. Tools included are: 

rt-shifts: calculates retention time shifts.
blank-effect: determines the blank effect (percentage) of each compound.
qc-correction: applies qc-correction to the data.
qc-rsd: determines RSD QC.
is-rsd: determines RSD of the internal standard(s).
rep-rsd: determines RSD replicates.
export-measurements: as sample/compound matrix.
plot-compounds: plots the retention time shifts, area, internal standard, and qc-corrected information of all compounds.

### CODE REVIEW

**Comment by pcm32** [comment]
You don't want this for the release?

**Comment by michaelvanvliet** [comment]
@pcm32 Yes, I want this in the release. You mean I should have made a PR to the new release branch? Or is something still wrong?

**Comment by michaelvanvliet** [comment]
Closing this as it is the same as https://github.com/phnmnl/container-galaxy-k8s-runtime/pull/232 , which will be merged back to the develop branch after the release.

**Comment by pcm32** [comment]
No, I didn't mean that there would be anything wrong, only to choose the correct branch to merge to for the release :-).

**Pull request closed without merging**
